# MONITOR SETUP

monitorv2 {
    output = DP-2
    mode = highres@highrr
    position = 2560x-500
    scale = 1.5
    transform = 3
    supports_wide_color = 1
    supports_hdr = 1
    icc = /usr/share/color/icc/colord/AppleRGB.icc
}

monitorv2 {
    output = DP-1
    mode = highres@highrr
    position = 0x0
    scale = 1.5
    transform = 0
    supports_wide_color = 1
    supports_hdr = 1
    icc = /usr/share/color/icc/colord/AppleRGB.icc
}

#worspaces
workspace=1, monitor:DP-1,  default:true
workspace=2, monitor:DP-2,  default:true

input {
    kb_layout = pl
    #  kb_variant = ,qwerty
    sensitivity = -0.5 # -1.0 to 1.0, 0 means no modification.
}

