# Autostart

#exec-once = waybar # status bar
exec-once = mako #notifications
exec-once = systemctl --user start hyprpolkitagent #auth manager
exec-once = nm-applet # networkmanager applet
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data
exec-once = hpaper start # wallpaper daemon
exec-once = hypridle #screen lock
exec-once = easyeffects --gapplication-service # equalizer
exec-once = systemctl --user enable opentabletdriver.service --now #tablet driver service
