# Layers
layerrule = blur on, match:namespace launcher
layerrule = blur on, match:namespace notifications
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar

windowrule {
    name = poe2-overlay

    match:class = exiled-exchange-2
    animation = none
    border_size = 0
    no_shadow = on
    no_blur = on
}

#Suppress automated maximization of new windows
#windowrule = suppressevent maximize, class:.*

#windowrulev2 = pseudotile, class:.*ghostty
windowrule {
    name = ghostty-conf
    match:class = .*ghostty

    float = on
    size = 1300 1000
}

#start all games on primary monitor
windowrule {
    name = game-rules

    content = game
    workspace = 1
}

windowrule {
  name = AC
  no_anim = on
  pin = on
  float = on
  fullscreen_state = on
  move = 0 0
  match:class = steam_app_3058630
}

windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}
