# Layers
layerrule = blur on, match:namespace launcher
layerrule = blur on, match:namespace notifications
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar

windowrule {
    name = poe2-overlay

    match:class = exiled-exchange-2
    animation = none
    border_size = 0
    no_shadow = on
    no_blur = on
}

#Suppress automated maximization of new windows
#windowrule = suppressevent maximize, class:.*

#windowrulev2 = pseudotile, class:.*ghostty
windowrule {
    name = ghostty-conf
    match:class = .*ghostty

    float = on
    size = 1300 1000
}

#start all games on primary monitor
windowrule {
    name = game-rules

    content = game
    workspace = 1
}
