# Layers
layerrule = blur, launcher
layerrule = blur, notifications
layerrule = blur, waybar
layerrule = ignorezero, waybar

windowrulev2 = noanim, class:exiled-exchange-2
windowrulev2 = noborder, class:exiled-exchange-2
windowrulev2 = noshadow, class:exiled-exchange-2
windowrulev2 = noblur, class:exiled-exchange-2

#Suppress automated maximization of new windows
windowrulev2 = suppressevent maximize, class:.*

#windowrulev2 = pseudotile, class:.*ghostty
windowrulev2 = float, class:.*ghostty
windowrulev2 = size 1300 1000, class:.*ghostty

#start all games on primary monitor
windowrulev2 = workspace 1, content:game
